/* Polished existing platformer: supplied hero, forest layers and platform atlas only. */
const WIDTH=960,HEIGHT=540,WORLD_WIDTH=7680,LAST_LEVEL=10;
const gameState={level:1,lives:3,coins:0,score:0,speed:0,jump:0,fireTier:1,locked:false};
const paths={playerIdle:'assets/sample-source/idle/sprite sheets/idle.png',playerWalk:'assets/sample-source/walk/sprite sheets/walk.png',monster:'assets/monster-source/1 Pink_Monster/Pink_Monster_Walk_6.png',owletBoss:'assets/monster-source/2 Owlet_Monster/Owlet_Monster_Walk_6.png',boss:'assets/monster-source/3 Dude_Monster/Dude_Monster_Walk_6.png',forestBack:'assets/forest-back.png',forestMist:'assets/forest-mist.png',platformAtlas:'assets/platform-atlas.png',platformLong:'assets/platform-long.png',platformMedium:'assets/platform-medium.png',platformSlope:'assets/platform-slope.png',platformCurved:'assets/platform-curved.png',platformSmall:'assets/platform-small.png',checkpointFlag:'assets/checkpoint-flag.png'};
const bossProfiles=[
  {name:'EMBER OGRE',texture:'pink-monster',animation:'monster-walk',color:0xff966b,attack:'slam',scale:3.3},
  {name:'SKY STALKER',texture:'owlet-boss',animation:'owlet-boss-walk',color:0x89e5ff,attack:'lunge',scale:3.3},
  {name:'ASH WARDEN',texture:'dude-boss',animation:'boss-walk',color:0xb994ff,attack:'fire',scale:3.4}
];

class AssetPipeline{
  static load(scene){scene.load.spritesheet('player-idle',paths.playerIdle,{frameWidth:46,frameHeight:55});scene.load.spritesheet('player-walk',paths.playerWalk,{frameWidth:45,frameHeight:58});scene.load.spritesheet('pink-monster',paths.monster,{frameWidth:32,frameHeight:32});scene.load.spritesheet('owlet-boss',paths.owletBoss,{frameWidth:32,frameHeight:32});scene.load.spritesheet('dude-boss',paths.boss,{frameWidth:32,frameHeight:32});scene.load.spritesheet('checkpoint-flag',paths.checkpointFlag,{frameWidth:529,frameHeight:991});['forestBack','forestMist','platformAtlas','platformLong','platformMedium','platformSlope','platformCurved','platformSmall'].forEach(key=>scene.load.image(key==='platformAtlas'?'platform-atlas':key.replace(/[A-Z]/g,letter=>`-${letter.toLowerCase()}`),paths[key]));}
  static prepare(scene){if(!scene.anims.exists('hero-idle')){scene.anims.create({key:'hero-idle',frames:scene.anims.generateFrameNumbers('player-idle',{start:0,end:9}),frameRate:10,repeat:-1});scene.anims.create({key:'hero-walk',frames:scene.anims.generateFrameNumbers('player-walk',{start:0,end:3}),frameRate:10,repeat:-1});scene.anims.create({key:'monster-walk',frames:scene.anims.generateFrameNumbers('pink-monster',{start:0,end:5}),frameRate:8,repeat:-1});scene.anims.create({key:'owlet-boss-walk',frames:scene.anims.generateFrameNumbers('owlet-boss',{start:0,end:5}),frameRate:7,repeat:-1});scene.anims.create({key:'boss-walk',frames:scene.anims.generateFrameNumbers('dude-boss',{start:0,end:5}),frameRate:7,repeat:-1});scene.anims.create({key:'flag-idle',frames:[{key:'checkpoint-flag',frame:0}],frameRate:2,repeat:-1});scene.anims.create({key:'flag-raise',frames:[{key:'checkpoint-flag',frame:1}],frameRate:1,repeat:0});scene.anims.create({key:'flag-active',frames:[{key:'checkpoint-flag',frame:2}],frameRate:2,repeat:-1});}
    const atlas=scene.textures.get('platform-atlas');if(atlas.has('checkpoint'))return;
    atlas.add('checkpoint',0,1100,365,205,610);atlas.add('exit',0,1330,650,175,325);
  }
}

class PlatformArt{
  static keys={long:'platform-long',medium:'platform-medium',wide:'platform-curved',curved:'platform-curved',small:'platform-small',slope:'platform-slope'};
  /* Measured from the alpha art: the dense, continuous grass line—not the transparent canvas edge. */
  static surface={long:54,medium:37,wide:45,curved:45,small:27,slope:73};
  static place(group,frame,x,y){
    const scene=group.scene,art=scene.add.image(x,y,this.keys[frame]).setOrigin(.5,0);
    /* Art PNGs have transparent canvas above the grass. Collision is a separate top-only strip. */
    const surfaceY=y+this.surface[frame],floor=scene.add.zone(x,surfaceY+9,art.width,18).setOrigin(.5);
    scene.physics.add.existing(floor,true);group.add(floor);floor.platformArt=art;return art;
  }
  static slope(group,x,y){const art=group.scene.add.image(x,y,'platform-slope').setOrigin(.5,0);
    /* Arcade Physics has no slope primitive. These invisible 8px top strips trace the visible incline. */
    for(let i=0;i<10;i++){const step=group.scene.add.zone(x-art.width/2+32+i*62,y+120-i*11,66,12).setOrigin(.5);group.scene.physics.add.existing(step,true);group.add(step);}return art;}
}

class ForestParallax{
  constructor(scene){this.scene=scene;this.width=930;this.layers=[this.make('forest-back',.15,1),this.make('forest-mist',.35,.88)];}
  make(key,speed,alpha){const sprites=[];for(let i=-2;i<5;i++){const sprite=this.scene.add.image(0,0,key).setOrigin(.5,0).setDisplaySize(this.width,HEIGHT).setScrollFactor(0).setDepth(-20+speed).setAlpha(alpha);sprite.setFlipX(Math.abs(i)%4===3);sprites.push(sprite);}return{speed,sprites};}
  update(cameraX){this.layers.forEach(layer=>{const offset=-(cameraX*layer.speed%this.width);layer.sprites.forEach((sprite,i)=>sprite.x=offset+(i-2)*this.width+this.width/2);});}
  destroy(){this.layers.forEach(layer=>layer.sprites.forEach(sprite=>sprite.destroy()));}
}

class LevelBuilder{
  static blueprint(level){const hill=level%2?'curved':'wide';return [
    /* Handcrafted chunks: flat start → raised route → compact encounter → checkpoint → exit. */
    {frame:'long',x:400,y:400},{frame:'small',x:1000,y:360},{frame:'medium',x:1370,y:400},{frame:hill,x:2000,y:400},
    {frame:'long',x:2850,y:400},{frame:'curved',x:3700,y:400},{frame:'long',x:4550,y:400},
    {frame:'small',x:5300,y:360},{frame:'medium',x:5700,y:400},{frame:'wide',x:6400,y:400},{frame:'long',x:7280,y:400}
  ];}
  static build(scene,level){const ground=scene.physics.add.staticGroup(),spikes=scene.physics.add.staticGroup(),coins=scene.physics.add.group({allowGravity:false,immovable:true}),pieces=this.blueprint(level),enemySpots=[];
    pieces.forEach(piece=>{const art=PlatformArt.place(ground,piece.frame,piece.x,piece.y);piece.surfaceY=piece.y+PlatformArt.surface[piece.frame];piece.left=piece.x-art.width/2;piece.right=piece.x+art.width/2;});
    /* Deliberate route rewards: raised coin pairs and a sparse ground path. */
    [[1000,360,'small'],[1370,400,'medium'],[3700,400,'curved'],[5300,360,'small'],[5700,400,'medium']].forEach(([x,y,frame])=>coins.create(x,y+PlatformArt.surface[frame]-30,'coin'));
    coins.create(1045,360+PlatformArt.surface.small-30,'coin');coins.create(5350,360+PlatformArt.surface.small-30,'coin');
    [2,5,8].forEach(index=>{const piece=pieces[index];enemySpots.push({x:piece.x,y:piece.surfaceY-28,left:piece.left+30,right:piece.right-30});});
    return{ground,spikes,coins,enemySpots};
  }
}

class QuestScene extends Phaser.Scene{
  constructor(){super('quest')}
  preload(){AssetPipeline.load(this)}
  create(){this.makeUtilityTextures();AssetPipeline.prepare(this);this.parallax=new ForestParallax(this);this.buildLevel();this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.parallax?.destroy());}
  makeUtilityTextures(){if(this.textures.exists('spike'))return;const g=this.make.graphics({add:false});g.fillStyle(0xe6f6ff).fillTriangle(0,24,12,2,24,24);g.lineStyle(2,0x74c9f0).strokeTriangle(0,24,12,2,24,24);g.generateTexture('spike',24,24);g.clear();g.fillStyle(0xffd45c).fillCircle(8,8,8);g.lineStyle(2,0xfff0a4).strokeCircle(8,8,6);g.generateTexture('coin',16,16);g.clear();g.fillStyle(0xff4d32).fillCircle(9,9,9);g.fillStyle(0xffbc42).fillCircle(7,7,5);g.fillStyle(0xfff4b0).fillCircle(5,5,2);g.generateTexture('fireball',18,18);}
  buildLevel(){this.physics.world.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.level=LevelBuilder.build(this,gameState.level);this.player=this.physics.add.sprite(110,355,'player-idle',0).setOrigin(.5,1).setScale(1.05).setCollideWorldBounds(true).play('hero-idle');this.player.body.setSize(28,31).setOffset(9,24);this.player.body.setMaxVelocity(350,720);this.player.jumpsUsed=0;this.player.wasGrounded=false;this.facing=1;this.nextShotAt=0;this.respawn={x:110,y:355};this.invulnerableUntil=0;this.cameraFloor=0;this.keys=this.input.keyboard.addKeys('LEFT,RIGHT,UP,A,D,W,SPACE,F');
    this.physics.add.collider(this.player,this.level.ground);this.physics.add.overlap(this.player,this.level.spikes,()=>this.damage());this.physics.add.overlap(this.player,this.level.coins,(_,coin)=>this.collectCoin(coin));
    this.enemies=this.physics.add.group();this.createEnemies();this.physics.add.collider(this.enemies,this.level.ground);this.physics.add.collider(this.player,this.enemies,this.hitEnemy,undefined,this);this.fireballs=this.physics.add.group({allowGravity:false});this.physics.add.collider(this.fireballs,this.level.ground,fireball=>fireball.destroy());this.physics.add.overlap(this.fireballs,this.enemies,(fireball,enemy)=>this.hitEnemyWithFireball(fireball,enemy));
    /* The transparent sheet has 135px below the stone base; compensate so its real base sits on grass. */
    this.checkpoint=this.add.sprite(4550,500,'checkpoint-flag',0).setOrigin(.5,1).setScale(.34).play('flag-idle');this.checkpointTrigger=this.add.zone(4550,402,86,105).setOrigin(.5);this.physics.add.existing(this.checkpointTrigger,true);this.physics.add.overlap(this.player,this.checkpointTrigger,()=>this.activateCheckpoint());
    this.exit=this.add.sprite(7565,488,'checkpoint-flag',0).setOrigin(.5,1).setScale(.25).play('flag-idle');this.exitTrigger=this.add.zone(7565,400,88,115).setOrigin(.5);this.physics.add.existing(this.exitTrigger,true);this.physics.add.overlap(this.player,this.exitTrigger,()=>{if(!this.boss?.active)this.finishLevel();});
    this.createBoss();this.createHud();this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setDeadzone(210,80);this.cameras.main.fadeIn(180,0,0,0);
  }
  createEnemies(){this.level.enemySpots.forEach((spot,i)=>{const enemy=this.enemies.create(spot.x,spot.y,'pink-monster',0).setScale(1.15).play('monster-walk');enemy.body.setSize(27,30).setOffset(2,2);enemy.leftBound=spot.left;enemy.rightBound=spot.right;enemy.setVelocityX(i%2?-55:55);});}
  createHud(){this.hud=this.add.text(15,14,'',{fontFamily:'monospace',fontStyle:'bold',fontSize:'18px',color:'#fff',stroke:'#12212c',strokeThickness:5}).setScrollFactor(0).setDepth(30);this.updateHud()}
  updateHud(){this.hud.setText(`LIVES ${gameState.lives}   SCORE ${gameState.score}   COINS ${gameState.coins}   LEVEL ${gameState.level}/${LAST_LEVEL}`)}
  update(time,delta){this.parallax.update(this.cameras.main.scrollX);if(gameState.locked)return;const p=this.player,left=this.keys.LEFT.isDown||this.keys.A.isDown,right=this.keys.RIGHT.isDown||this.keys.D.isDown,jump=Phaser.Input.Keyboard.JustDown(this.keys.UP)||Phaser.Input.Keyboard.JustDown(this.keys.W)||Phaser.Input.Keyboard.JustDown(this.keys.SPACE),shoot=Phaser.Input.Keyboard.JustDown(this.keys.F),speed=245+gameState.speed*35,grounded=p.body.blocked.down||p.body.touching.down;p.setAccelerationX(left?-1350:right?1350:0).setDragX(grounded?1550:230).setMaxVelocity(speed,720);if(grounded)p.jumpsUsed=0;if(jump&&p.jumpsUsed<2){p.setVelocityY(p.jumpsUsed===0?-470-gameState.jump*40:-430-gameState.jump*35);p.jumpsUsed++;}if(left)this.facing=-1;if(right)this.facing=1;if(shoot)this.shootFireball();if(Math.abs(p.body.velocity.x)>14){p.setFlipX(p.body.velocity.x>0);p.play('hero-walk',true)}else p.play('hero-idle',true);this.enemies.children.iterate(enemy=>{if(!enemy?.active)return;if(enemy.x<=enemy.leftBound||enemy.x>=enemy.rightBound)enemy.setVelocityX(-enemy.body.velocity.x);});this.updateBossAI(delta);if(this.bossPanel?.active)this.bossPanel.setVisible(!!this.boss?.active&&Phaser.Math.Distance.Between(p.x,p.y,this.boss.x,this.boss.y)<440);const camera=this.cameras.main;if(camera.scrollX<this.cameraFloor)camera.scrollX=this.cameraFloor;this.cameraFloor=camera.scrollX;const forwardBarrier=camera.scrollX+34;if(p.x<forwardBarrier){p.x=forwardBarrier;p.body.velocity.x=Math.max(0,p.body.velocity.x);}if(p.y>570)this.damage();}
  collectCoin(coin){if(!coin.active)return;coin.disableBody(true,true);gameState.coins+=5;gameState.score+=500;this.updateHud()}
  shootFireball(){if(this.time.now<this.nextShotAt)return;this.nextShotAt=this.time.now+(gameState.fireTier===3?180:260);if(gameState.fireTier===3)[-12,0,12].forEach(offset=>this.launchFireball(offset,2,520,1));else this.launchFireball(0,gameState.fireTier===2?2:1,gameState.fireTier===2?490:430,gameState.fireTier===2?1.3:1);}
  launchFireball(offsetY,damage,speed,scale){const fireball=this.fireballs.create(this.player.x+this.facing*26,this.player.y-34+offsetY,'fireball').setScale(scale);fireball.damage=damage;fireball.setCircle(7).setVelocityX(this.facing*speed);fireball.body.allowGravity=false;fireball.setAngularVelocity(this.facing*480);this.time.delayedCall(1150,()=>{if(fireball.active)fireball.destroy();});}
  hitEnemyWithFireball(fireball,enemy){if(!fireball.active||!enemy.active)return;fireball.destroy();enemy.setVelocity(0,0);enemy.setTint(0xff9a74);this.tweens.add({targets:enemy,scaleX:0.2,scaleY:0.15,alpha:0,duration:180,onComplete:()=>enemy.destroy()});gameState.coins+=10;gameState.score+=500;this.updateHud();}
  hitEnemy(player,enemy){if(!enemy.active||gameState.locked)return;if(player.body.velocity.y>85&&player.y<enemy.y-8){enemy.disableBody(true,true);player.setVelocityY(-315);gameState.score+=250;this.updateHud();}else if(this.time.now>=this.invulnerableUntil)this.damage();}
  activateCheckpoint(){if(this.checkpoint.raised)return;this.checkpoint.raised=true;this.respawn={x:this.checkpoint.x,y:355};this.checkpoint.play('flag-raise');this.time.delayedCall(360,()=>this.checkpoint.play('flag-active'));for(let i=0;i<14;i++){const spark=this.add.circle(this.checkpoint.x+Phaser.Math.Between(-34,34),this.checkpoint.y-Phaser.Math.Between(60,190),3,0x83eaff).setDepth(8);this.tweens.add({targets:spark,y:spark.y-34,alpha:0,duration:500,delay:i*18,onComplete:()=>spark.destroy()});}gameState.coins+=10;gameState.score+=500;this.updateHud()}
  damage(){if(gameState.locked||this.time.now<this.invulnerableUntil)return;gameState.locked=true;gameState.lives--;this.updateHud();this.cameras.main.shake(130,.01);if(gameState.lives<0){this.showPanel('GAME OVER','The forest awaits your return.','Restart level',()=>this.restartLevel());return;}this.player.disableBody(true,true);this.time.delayedCall(620,()=>this.respawnPlayer());}
  respawnPlayer(){this.player.enableBody(true,this.respawn.x,this.respawn.y,true,true);this.player.body.setSize(28,31).setOffset(9,24);this.player.jumpsUsed=0;this.player.setVelocity(0,0).setAcceleration(0,0).setAlpha(.45);this.cameraFloor=Math.max(0,this.respawn.x-210);this.cameras.main.stopFollow();this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.cameras.main.setScroll(this.cameraFloor,0);this.cameras.main.startFollow(this.player,true,.09,.09);this.invulnerableUntil=this.time.now+1500;this.tweens.add({targets:this.player,alpha:1,duration:1500,onComplete:()=>gameState.locked=false});}
  restartLevel(){this.hidePanel();gameState.lives=3;gameState.locked=false;this.cameras.main.resetFX();this.cameras.main.stopFollow();this.scene.restart();}
  finishLevel(){if(gameState.locked)return;gameState.locked=true;this.player.setAcceleration(0,0).setVelocity(0,0);this.player.body.enable=false;this.tweens.add({targets:this.player,scaleX:1.35,scaleY:1.35,alpha:.1,duration:320});this.cameras.main.fadeOut(360,5,18,25);this.time.delayedCall(390,()=>{if(gameState.level===LAST_LEVEL)this.showPanel('VICTORY!','The Ice Warden has fallen.\n\nThanks for playing High Forest Quest.','Play again',()=>location.reload());else{gameState.level++;gameState.locked=false;this.scene.restart();}});}
  createBoss(){const finalBoss=gameState.level===LAST_LEVEL;this.boss=this.add.sprite(7200,454,'dude-boss',0).setOrigin(.5,1).setScale(finalBoss?3.8:3.2).setTint(finalBoss?0xa6eaff:0xffbd6c).play('boss-walk');this.boss.hp=this.boss.maxHp=finalBoss?12:7;this.boss.nextHitAt=0;this.bossHitbox=this.add.zone(7200,414,84,80).setOrigin(.5);this.physics.add.existing(this.bossHitbox,true);this.physics.add.collider(this.player,this.bossHitbox,()=>this.damage());this.physics.add.overlap(this.fireballs,this.bossHitbox,(first,second)=>this.hitBossWithFireball(first?.texture?.key==='fireball'?first:second));
    this.bossPanel=this.add.container(WIDTH/2,68).setScrollFactor(0).setDepth(40).setVisible(false);const panel=this.add.rectangle(0,0,310,52,0x09131d,.9).setStrokeStyle(2,0xf5bf57),track=this.add.rectangle(0,12,248,14,0x2a1820).setStrokeStyle(1,0xffd27c),fill=this.add.rectangle(-123,12,244,10,0xe84c45).setOrigin(0,.5),label=this.add.text(0,-13,finalBoss?'ICE WARDEN':'FOREST GUARDIAN',{fontFamily:'monospace',fontStyle:'bold',fontSize:'15px',color:'#fff2c8'}).setOrigin(.5);this.bossPanel.add([panel,track,fill,label]);this.bossFill=fill;this.bossLabel=label;this.updateBossHud();}
  hitBossWithFireball(fireball){const boss=this.boss;if(!fireball?.active||!boss?.active||this.time.now<boss.nextHitAt)return;boss.nextHitAt=this.time.now+120;fireball.destroy();boss.hp--;boss.setTint(0xfff2a3);this.time.delayedCall(80,()=>{if(boss.active)boss.setTint(gameState.level===LAST_LEVEL?0xa6eaff:0xffbd6c);});this.updateBossHud();if(boss.hp<=0){this.bossHitbox.destroy();boss.destroy();this.bossPanel.destroy();gameState.coins+=30;gameState.score+=2500;this.updateHud();}}
  updateBossHud(){if(!this.bossPanel?.active||!this.boss?.active)return;this.bossFill.width=244*(this.boss.hp/this.boss.maxHp);this.bossLabel.setText(`${gameState.level===LAST_LEVEL?'ICE WARDEN':'FOREST GUARDIAN'}  ${this.boss.hp}/${this.boss.maxHp}`);}
  showPanel(title,body,label,action){const panel=document.querySelector('#message');panel.querySelector('h1').textContent=title;panel.querySelector('p').textContent=body;const button=panel.querySelector('#action');button.textContent=label;button.onclick=action;panel.classList.remove('hidden')}
  hidePanel(){const panel=document.querySelector('#message');panel.classList.add('hidden');panel.querySelector('#action').onclick=null;}
}
const game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:WIDTH,height:HEIGHT,pixelArt:true,physics:{default:'arcade',arcade:{gravity:{y:1050},debug:false}},scene:QuestScene});
const shop=document.querySelector('#shop');document.querySelector('#shopButton').onclick=()=>shop.classList.remove('hidden');document.querySelector('#closeShop').onclick=()=>shop.classList.add('hidden');shop.querySelectorAll('[data-upgrade]').forEach(button=>{const type=button.dataset.upgrade,cost=type==='speed'?5:8;button.textContent=type==='speed'?'Swift Boots · 5 coins':'Moon Feather · 8 coins';button.onclick=()=>{if(gameState.coins>=cost&&gameState[type]<3){gameState.coins-=cost;gameState[type]++;button.textContent=type==='speed'?`Swift Boots · ${gameState.speed}/3`:`Moon Feather · ${gameState.jump}/3`;game.scene.getScene('quest').updateHud()}}});
